name: Set Up JDK
description: Set up Java Development Kit (JDK) for building Java projects.

inputs:
  java-version:
    description: 'Version of JDK to set up'
    required: true
    default: '11'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
