name: Publish to Artifactory
description: Publish the built artifact to Artifactory.

runs:
  using: "composite"
  steps:
    - name: Publish to Artifactory
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
             -T target/your-artifact.jar \
             "$ARTIFACTORY_URL/path/to/repository/your-artifact.jar"
