name: SonarQube Scan
description: Run SonarQube code analysis.

runs:
  using: "composite"
  steps:
    - name: SonarQube Scan
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar
