# action.yml in actions/environment_setup
name: action: Environment_Setup
description: "Setup Node.js and install dependencies"
inputs:
  node-version:
    description: "Node.js version"
    default: "21"

runs:
  using: "composite"
  steps:
    - name: Checkout code - thru action 
      uses: actions/checkout@v3

    - name: Set up Node.js - thru action 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies - thru action 
      run: npm install
