# main_action_test.yml in the workflow
name: NodeJS CI action test Pipe

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Test
        uses: nanjansudhakar/github_actions_library/.github/actions/environment_setup@main
        with:
          node-version: '20'
