# main.yml in another repository
name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: nanjansudhakar/github_actions_library/.github/workflows/reusable-workflow.yml@main
    with:
      environment: development
