# reusable-workflow.yml in .github/workflows
name: Reusable CI/CD Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code - thru workflows
        uses: actions/checkout@v3

      - name: Run build - thru workflows
        run: echo "Building the project..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to ${{ inputs.environment }}  - thru workflows
        run: echo "Deploying to ${{ inputs.environment }}..."
